version: "3"
services:
  myapp:
    image: ghcr.io/paerck25/myimage:latest
    ports:
      - "80:3000"
    depends_on:
      - db
    volumes:
      - ./files:/upload
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./db:/var/lib/postgresql/data
