# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - madein-server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: "배포"
    runs-on: ubuntu-latest
    env:
      SSH_HOSTNAME: ec2-54-180-30-7.ap-northeast-2.compute.amazonaws.com
      SSH_USER_NAME: ubuntu
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DOCKER_COMPOSE_PATH: ~/madein-server
    steps:
      - uses: actions/checkout@v2

      - name: docker-compose.yml 업로드
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SSH_HOSTNAME }}
          username: ${{ env.SSH_USER_NAME }}
          key: ${{ env.SSH_KEY }}
          source: ./docker-compose.yml
          target: ${{ env.DOCKER_COMPOSE_PATH }}
          overwrite: true

      - name: Docker 이미지 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST_NAME }}
          username: ${{ env.SSH_USER_NAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd ${{ env.DOCKER_COMPOSE_PATH }}
            docker pull ghcr.io/${{ github.repository_owner }}/docker-test:${{ needs.build.outputs.tag }}
            TAG=${{ needs.build.outputs.tag }} docker-compose up -d
            docker tag ghcr.io/${{ github.repository_owner }}/docker-test:${{ needs.build.outputs.tag }} ghcr.io/${{ github.repository_owner }}/docker-test:latest
